import flowbite from "flowbite-react/tailwind";

/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "selector",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}", flowbite.content()],
  theme: {
    borderRadius: {
      xs: "4px",
      s: "8px",
      m: "12px",
      lg: "16px",
      full: "100%",
    },
    extend: {
      colors: {
        gray: {
          650: "#414b5a",
          750: "#2b3544",
        },
        "light-primary": "#FFFFFF",
        "light-secondary": "#F5F5F5",
        "dark-primary": "#1F2A37",
        "dark-secondary": "#111928",
      },
      boxShadow: {
        "sharp-dark-top": "inset 0 1px 0 0 rgba(0, 0, 0, .09)",
        "sharp-dark-buttom": "0px 3px 7px -3px rgba(0, 0, 0, .2)",
        "sharp-dark":
          "inset 0 1px 0 0 rgba(0, 0, 0, .09), 0px 3px 7px -3px rgba(0, 0, 0, .2)",
        "sharp-light-top": "inset 0 1px 0 0 rgba(255, 255, 255, .06)",
        "sharp-light-buttom": "0px 3px 7px -3px rgba(0, 0, 0, 0.3)",
        "sharp-light":
          "inset 0 1px 0 0 rgba(255, 255, 255, .06), 0px 3px 7px -3px rgba(0, 0, 0, 0.3)",
      },

      animation: {
        fill: "fill",
        "fade-fwd": "fade-fwd 0.4s ease-in-out both",
        "slide-in": "slide-in 0.6s cubic-bezier(.65,.09,.31,1.17) both",
        "scale-up":
          "scale-up 0.6s .3s cubic-bezier(.65,.09,.31,1.17) alternate both", // if change made in the delay you must change the 3rd argument in the cubic-bezier for the scale-down animation
        "scale-down":
          "scale-down 0.6s cubic-bezier(.53,.01,.3,.99) alternate both",
      },

      keyframes: {
        fill: {
          "0%": { width: "0%" },
          "100%": { width: "100%" },
        },
        "fade-fwd": {
          "0%": {
            "-webkit-transform": "translateZ(-80px)",
            transform: "translateZ(-80px)",
            opacity: 0,
          },
          "100%": {
            "-webkit-transform": "translateZ(0)",
            transform: "translateZ(0)",
            opacity: 1,
          },
        },
        "slide-in": {
          "0%": {
            "-webkit-transform": "translateY(-1000px)",
            transform: "translateY(-1000px)",
            opacity: 0,
          },
          "100%": {
            "-webkit-transform": "translateY(0)",
            transform: "translateY(0)",
            opacity: 1,
          },
        },
        "scale-up": {
          "0%": {
            "max-height": 0,
          },
          "100%": {
            "max-height": "999px",
          },
        },
        "scale-down": {
          "0%": {
            "max-height": "999px",
          },
          "100%": {
            "max-height": 0,
          },
        },
      },
    },
  },
  plugins: [flowbite.plugin()],
};

/* ----------------------------------------------
 * Generated by Animista on 2024-11-7 18:44:4
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation fade-in-fwd
 * ----------------------------------------
 */
